"""Initial migration

Revision ID: e61e0fed1312
Revises: 
Create Date: 2026-02-19 01:13:59.029347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61e0fed1312'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hospital_id', 'hospitals', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospitals_hospital_id'), 'hospitals', ['hospital_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admission_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('admissions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'date', name='uq_hospital_date')
    )
    op.create_index('idx_admission_hospital_date', 'admission_history', ['hospital_id', 'date'], unique=False)
    op.create_table('forecast_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('hospital_count', sa.Integer(), nullable=False),
    sa.Column('horizon_count', sa.Integer(), nullable=False),
    sa.Column('total_forecasts', sa.Integer(), nullable=False),
    sa.Column('inference_time_seconds', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecast_run_created', 'forecast_runs', ['created_at'], unique=False)
    op.create_index('idx_forecast_run_user', 'forecast_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_forecast_runs_created_at'), 'forecast_runs', ['created_at'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('forecast_run_id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'forecast_date', 'horizon', name='uq_hospital_date_horizon')
    )
    op.create_index('idx_forecast_horizon', 'forecasts', ['horizon'], unique=False)
    op.create_index('idx_forecast_hospital_date', 'forecasts', ['hospital_id', 'forecast_date'], unique=False)
    op.create_index('idx_forecast_run', 'forecasts', ['forecast_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_forecast_run', table_name='forecasts')
    op.drop_index('idx_forecast_hospital_date', table_name='forecasts')
    op.drop_index('idx_forecast_horizon', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_forecast_runs_created_at'), table_name='forecast_runs')
    op.drop_index('idx_forecast_run_user', table_name='forecast_runs')
    op.drop_index('idx_forecast_run_created', table_name='forecast_runs')
    op.drop_table('forecast_runs')
    op.drop_index('idx_admission_hospital_date', table_name='admission_history')
    op.drop_table('admission_history')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hospitals_hospital_id'), table_name='hospitals')
    op.drop_index('idx_hospital_id', table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
